### ISSUE TITLE
Tasks are not ordered as it is listed in Makefile

### ISSUE THREAD

**Issue by monim67** [carlos-algms/vscode-make-task-provider#1]
In Makefile tasks sidebar section the tasks are listed randomly not in the same order as listed in the Makefile.

![image](https://user-images.githubusercontent.com/6266677/103676946-ea124580-4fab-11eb-9d7d-ec626171a40c.png)

**Vs-code info:**

Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-58-generic snap

**Comment by carlos-algms** [comment]
Hey, thanks for using the extension and taking your time to report the issue.
sorry for the late reply, but I think I did not receive a notification from Github. 

I will double-check because it also seems that you are receiving duplicated tasks. 

I the meantime, could you please check if the extension is updated and send me the result of:

```shell
make --version
```

**Comment by monim67** [comment]
My make version is as below. I don't see tasks duplicated anymore. But as I recall the duplicated tasks were calling `nmake` commands of the same tasks. I am using a Ubuntu 20.04 64 bit OS.

```
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
```

**Comment by carlos-algms** [comment]
Nice to hear that you are not receiving duplicates anymore. 
It might have been fixed by a new release you got updated. 
Now if you have more than one `Makefile`, it will show you the path from where the tasks are coming from. 

![image](https://user-images.githubusercontent.com/4634613/105834897-5c82ae00-5fcb-11eb-88bb-93ac33257cd1.png)

Also, as you can see [Here on the source-code](https://github.com/carlos-algms/vscode-make-task-provider/blob/master/src/Tasks/getMakefileTargetNames.ts#L11) 
I basically run `$ make ... --print-only` to get the tasks from your Makefile, no `nmake` created code anywhere. 

Please, let me know if it happens again and we can debug further.

**Comment by monim67** [comment]
I can see the order of targets printed out by `make  --print-data-base` is not the same as the order in the Makefile. But the printed output contains the line number of each target. Can we use that to sort the targets?

```
#  recipe to execute (from 'Makefile', line 2):
                                       ^^^^^^
	python3 -m pip install --upgrade pip
	python3 -m pip install -r requirements.txt
```

**Comment by carlos-algms** [comment]
I don't think we can use the `line number`. 
I have Mac, and the output does not include the line numbers.

**Comment by carlos-algms** [comment]
Hello @monim67 sorry for the long wait. 
The extension version `2.1.0` was just released and it might fix your issue! 

The Pull-Request #11 migrated to a file-parser approach and it is now showing the Targets as they are defined in your `Makefile`. 

The next step will include a "Sort" functionality to allow you to order by Name also. 

If you manage to test it, please, let me know if your issue was fixed? 

Thanks.

**Comment by carlos-algms** [comment]
Closing by inactivity. 
No response from the author.
