### ISSUE TITLE
[bug] Extension list variables declared with ::= as targets

### ISSUE THREAD

**Issue by eathtespagheti** [carlos-algms/vscode-make-task-provider#12]
I usually declare simply expanded variables in my Makefiles according to POSIX standard (`::=` instead of `:=`), unfortunately the parser detect those variables as targets, not a big deal since it still detects everything else, but I think it's an easy fix worth the time

**Comment by carlos-algms** [comment]
Thank you very much for taking the time to report this. 
It seems indeed an easy fix. 

I really appreciate it when users come and report usages that I might have missed or never knew about it. 

When it is fixed I will report back.

**Comment by eathtespagheti** [comment]
Thank you for maintaining this extension, keep up with the good work!

**Comment by carlos-algms** [comment]
Hello again. 
I just published the new version `2.1.1` which inclues the fix for your issue 🎉 

The validation was missing  anything after the `:` and wrongly identifying variables as targets. 

Now you can set you variables as:

```
NAME = "Carlos"
LAST := "Gomes"
PKG ?= "vscode"
```

All of them should be ignored from now on. 

Please, let me know if it fixed your issue.

**Comment by carlos-algms** [comment]
Closing by inactivity. 
No response from the author.
