### ISSUE TITLE
Suggestion: show makefile directory in task list 

### ISSUE THREAD

**Issue by ilkka** [carlos-algms/vscode-make-task-provider#26]
This provider seems to discover targets from multiple makefiles just fine, but it would be really nice if it was possible to show the makefile directory name next to the task in the task list, if possible.

**Comment by carlos-algms** [comment]
Hey @ilkka, that is really a very important feature!!!
I'm currently struggling to decide on the right UX and how "readable" it is going to be. 

I do use the "NPM" extension and they do a good job of showing from which file the target is. 

NPM does have something like:

> **1 Target Name** - 2 origin folder (3 VSCode puts workspace automatically)
> _4 npm run xxxxxx_

I don't have item 4, which is a preview of the shell code to be executed, especially because Make can have multiline recipes, and the first line might not make sense 🤷🏻‍♂️

So I think it is going to be a "compact" list without proper spacing, and become difficult to read. 

### NPM example: 
![image](https://user-images.githubusercontent.com/4634613/172795627-ee61fd59-b30e-4b05-b2c3-2aecf7eca52d.png)


I will be working on this, and if you have any suggestions, please feel free to write them here.

**Comment by carlos-algms** [comment]
Which one do you think looks better? 
### A
The path on the second line
![image](https://user-images.githubusercontent.com/4634613/172896450-46e4b6d6-a7b7-4563-847c-1f7dbf564120.png)

### B
The path on the right side, no second line
![image](https://user-images.githubusercontent.com/4634613/172896781-a68d5ea5-3d99-47bf-91d0-4f576d43eda3.png)
