### ISSUE TITLE
Set path to make binary

### ISSUE THREAD

**Issue by itavero** [carlos-algms/vscode-make-task-provider#3]
Is it possible to set the path to the make binary?
We don't always use GNU Make, so I don't have make on my path, and have to use a specific path in order to run it.

**Comment by carlos-algms** [comment]
Hey, @itavero Thanks for using the Extensions and taking the time to request this feature.

I was just thinking about this option yesterday when I figured out that users without `make` in the `PATH` were not even able to see the task list.

I will try my best to deliver it as fast as possible, it is the 1st priority now.

**Comment by itavero** [comment]
Thanks for getting back to me so fast.
Just wondering if you also know what the minimum supported version of GNU Make is?

We're currently running GNU Make 4.0, but the `--print-data-base` (or `-p`) flag doesn't seem to work. It just starts the build instead.

**Comment by carlos-algms** [comment]
this is also another improvement, to increase the compatibility, we will try to parse the `Makefile` without using `make --***` at all. 
And the only failing point will be at execution time if `make` is not set or available in the `PATH`. 

The problem is when one has "linked" make files, 
I have no experience with this and it still cloudy on how to deal with that. 

First I will try to remove `--print-data-base` and stick only with `--just-print` 

![image](https://user-images.githubusercontent.com/4634613/106262292-1e7fc700-6223-11eb-8e65-436f36652e85.png)

**Comment by carlos-algms** [comment]
Hey @itavero, 
The release `v1.4.0` is alive and it includes the feature to set the path to your `make` executable, 
individually per Operating System: 
`make-task-provider.osx.makeExecutable`
`make-task-provider.unix.makeExecutable`
`make-task-provider.windows.makeExecutable`

Could you please check if it will suit your needs? 
Thanks.

**Comment by itavero** [comment]
Not sure when I'll have time to actually verify it, but looking at the code changes, it looks OK.

I'll close this issue for now. If it turns out that it doesn't work for me, I'll reopen it.
